#!/usr/bin/env bash

HOST="$(uname)"

# Let's make output snappy
black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[1;34m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'

export PATH=~/bin:$HOME/.deodex/bin:$PATH

export BBAKSMALIJAR=~/.deodex/binaries/baksmali.jar

export SSMALIJAR=~/.deodex/binaries/smali.jar

export VVDEXEXTRACTOR=~/.deodex/binaries/"$HOST"/vdexExtractor

export CCDEXCONVERTER=~/.deodex/binaries/"$HOST"/compact_dex_converter
